name: monkey_meal_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  animated_bottom_navigation_bar: ^1.4.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.1
  intl: ^0.18.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  uuid: ^4.5.1
  animated_notch_bottom_bar: ^1.0.3
  url_launcher: ^6.3.2
  flutter_map: ^8.2.1


flutter_icons:
  android: true
  background_color: "#ffffff"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 19

flutter_native_splash:
  image: 'assets/images/app_icon.png'
  color: "#FFFFFF"
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/fonts/Metropolis/

  fonts:
    - family: Metropolis
      fonts:
      - asset: assets/fonts/Metropolis/Metropolis-Regular.ttf
      - asset: assets/fonts/Metropolis/Metropolis-RegularItalic.ttf
        style: italic
      - asset: assets/fonts/Metropolis/Metropolis-Bold.ttf
        weight: 700
      - asset: assets/fonts/Metropolis/Metropolis-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: assets/fonts/Metropolis/Metropolis-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/Metropolis/Metropolis-ExtraBoldItalic.ttf
        style: italic
        weight: 900
      - asset: assets/fonts/Metropolis/Metropolis-Medium.ttf
        weight: 500
      - asset: assets/fonts/Metropolis/Metropolis-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Metropolis/Metropolis-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Metropolis/Metropolis-SemiBoldItalic.ttf
        weight: 600
        style: italic