// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJhgXUv-ou1N0Z4vm8hu9sce6pz-0dKg',
    appId: '1:1059656065152:web:443eda770d25bdc6050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    authDomain: 'meal-monkey-34c88.firebaseapp.com',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
    measurementId: 'G-DPBZZQEYXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1X3m0yVt3eAL5PYyMZBZPO1MRPVcwjcg',
    appId: '1:1059656065152:android:090bef2a6e26b30b050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGR0_7PbaFm8Pik--sUeTAs1mxIDM6EM',
    appId: '1:1059656065152:ios:c6f8ffab0f9c0d1c050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
    iosBundleId: 'com.example.monkeyMealProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGGR0_7PbaFm8Pik--sUeTAs1mxIDM6EM',
    appId: '1:1059656065152:ios:c6f8ffab0f9c0d1c050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
    iosBundleId: 'com.example.monkeyMealProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLJhgXUv-ou1N0Z4vm8hu9sce6pz-0dKg',
    appId: '1:1059656065152:web:93dee652c43432c1050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    authDomain: 'meal-monkey-34c88.firebaseapp.com',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
    measurementId: 'G-W8KN0X6FGL',
  );
}
